typography_spectrum: 0.9820547639392316
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30985018447972834
  lightness: 0.7750010800082237
  saturation: 0.22519587841816247
  rhythmicContrast: 0.37466388405300677
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4410901623778045
analytics:
  google: null
  facebook: null
  twitter: null
name: A Better Perspective®
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'No Ceiling, Just Sky™ Institute'
    url: 'http://www.noceilingjustskyinstitute.com'
    type: external
  - name: The Shadow Coach
    url: 'http://www.theshadowcoach.com'
    type: external
  - name: School of Shadow Coaching®
    url: 'http://www.schoolofshadowcoaching.com'
    type: external
favicon: null
title: No Ceiling...Just Sky™
purpose: []
