name: A Better Perspective®
favicon: null
layout_spectrum: 0.4410901623778045
typography_spectrum: 0.9820547639392316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30985018447972834
  lightness: 0.7750010800082237
  saturation: 0.22519587841816247
  rhythmicContrast: 0.37466388405300677
purpose: []
